apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Netology homework</title>
    </head>
    <body>
        <h1>Nginx in K8S</h1>
        <p>Web page was created via ConfigMap</p>
    </body>
    </html>
